services:
  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium
    restart: unless-stopped
    ports:
      - "4444:4444"
      - "7900:7900"
    shm_size: 2gb
    networks:
      - ci-network

networks:
  ci-network: